import Head from "next/head";
import Image from "next/image";
import AccessAlarmIcon from "@mui/icons-material/AccessAlarm";
import Box from "@mui/material/Box";
import {
  Avatar,
  Button,
  Card,
  CardContent,
  CardHeader,
  Collapse,
  Container,
  FormControl,
  Grid,
  IconButton,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  styled,
  TextField,
  Typography,
} from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { useState } from "react";
import { DesktopDatePicker } from "@mui/x-date-pickers/DesktopDatePicker";
import dayjs from "dayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

const ExpandMore = styled((props) => {
  const { expand, ...other } = props;
  return <IconButton {...other} />;
})(({ theme, expand }) => ({
  transform: !expand ? "rotate(0deg)" : "rotate(180deg)",
  marginLeft: "auto",
  transition: theme.transitions.create("transform", {
    duration: theme.transitions.duration.shortest,
  }),
}));

export default function Home() {
  const [expanded, setExpanded] = useState(false);
  const [value, setValue] = useState(dayjs(new Date()));

  const handleChange = (newValue) => {
    setValue(newValue);
  };

  const handleExpandClick = () => {
    setExpanded(!expanded);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <Box component="main" sx={{ mt: 5 }}>
          <Container maxWidth="lg">
            <Stack direction="row" justifyContent="space-between">
              <Typography component="h1" variant="h4">
                Online Registration
              </Typography>
              <Button variant="contained">Check Your Form Status</Button>
            </Stack>

            <Box component="form" sx={{ mt: 5 }}>
              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Instructions"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Typography paragraph marginBottom={0}>
                    Instructions here
                  </Typography>
                </CardContent>
              </Card>

              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Basic Details"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Grid container spacing={4}>
                    <Grid item container md={9} spacing={4}>
                      <Grid item md={4}>
                        <FormControl fullWidth>
                          <InputLabel id="demo-simple-select-label">
                            Type
                          </InputLabel>
                          <Select
                            labelId="demo-simple-select-label"
                            id="demo-simple-select"
                            label="Type"
                          >
                            <MenuItem value={10}>Ten</MenuItem>
                            <MenuItem value={20}>Twenty</MenuItem>
                            <MenuItem value={30}>Thirty</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                      <Grid item md={4}>
                        <TextField
                          fullWidth
                          label="First Name"
                          variant="outlined"
                        />
                      </Grid>
                      <Grid item md={4}>
                        <TextField
                          fullWidth
                          label="Last Name"
                          variant="outlined"
                        />
                      </Grid>
                      <Grid item md={4}>
                        <FormControl fullWidth>
                          <InputLabel id="demo-simple-select-label">
                            Gender
                          </InputLabel>
                          <Select label="Gender">
                            <MenuItem value={10}>Male</MenuItem>
                            <MenuItem value={20}>Female</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                      <Grid item md={4}>
                        <DesktopDatePicker
                          label="Date of Birth"
                          inputFormat="DD/MM/YYYY"
                          value={value}
                          onChange={handleChange}
                          renderInput={(params) => (
                            <TextField fullWidth {...params} />
                          )}
                        />
                      </Grid>
                      <Grid item md={4}>
                        <TextField
                          fullWidth
                          label="Mobile Number"
                          variant="outlined"
                        />
                      </Grid>
                      <Grid item md={4}>
                        <TextField fullWidth label="Email" variant="outlined" />
                      </Grid>
                      <Grid item md={4}>
                        <FormControl fullWidth>
                          <InputLabel id="demo-simple-select-label">
                            Blood Group
                          </InputLabel>
                          <Select label=" Blood Group">
                            <MenuItem value={10}>Ten</MenuItem>
                            <MenuItem value={20}>Twenty</MenuItem>
                            <MenuItem value={30}>Thirty</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                      <Grid item md={4}>
                        <FormControl fullWidth>
                          <InputLabel id="demo-simple-select-label">
                            Department
                          </InputLabel>
                          <Select label="Department">
                            <MenuItem value={10}>Ten</MenuItem>
                            <MenuItem value={20}>Twenty</MenuItem>
                            <MenuItem value={30}>Thirty</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                      <Grid item md={4}>
                        <FormControl fullWidth>
                          <InputLabel id="demo-simple-select-label">
                            Admission Session
                          </InputLabel>
                          <Select label="Admission Session">
                            <MenuItem value={10}>Ten</MenuItem>
                            <MenuItem value={20}>Twenty</MenuItem>
                            <MenuItem value={30}>Thirty</MenuItem>
                          </Select>
                        </FormControl>
                      </Grid>
                    </Grid>
                    <Grid item md={3} display="flex" justifyContent="center">
                      <Avatar
                        variant="rounded"
                        sx={{ width: 200, height: 250 }}
                        src="/broken-image.jpg"
                      />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>

              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Parent Details"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Grid container spacing={4}>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Name"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Number"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={6}></Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Mother's Name"
                        variant="outlined"
                      />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>

              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Parent Details"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Grid container spacing={4}>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Name"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Number"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={6}></Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Mother's Name"
                        variant="outlined"
                      />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>

              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Parent Details"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Grid container spacing={4}>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Name"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Number"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={6}></Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Mother's Name"
                        variant="outlined"
                      />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>

              <Card
                sx={{ border: "1px solid", borderColor: "#DEDEDE", my: 1 }}
                elevation={0}
              >
                <CardHeader
                  title="Parent Details"
                  sx={{
                    backgroundColor: "#F3F3F3",
                    borderBottom: "1px solid",
                    borderBottomColor: "#DEDEDE",
                  }}
                  titleTypographyProps={{
                    sx: { fontSize: 17, fontWeight: 600 },
                  }}
                />
                <CardContent>
                  <Grid container spacing={4}>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Name"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Father's Number"
                        variant="outlined"
                      />
                    </Grid>
                    <Grid item md={6}></Grid>
                    <Grid item md={3}>
                      <TextField
                        fullWidth
                        label="Mother's Name"
                        variant="outlined"
                      />
                    </Grid>
                  </Grid>
                </CardContent>
              </Card>
            </Box>
          </Container>
        </Box>
      </LocalizationProvider>
      <footer></footer>
    </div>
  );
}
